/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opencampusaccounting;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.*;
import static java.awt.font.TextAttribute.FONT;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class Sale extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Sale() {
        setTitle("Computerized Accounting");
        initComponents();
        addAll();
    }
    
    String [][]item={{"Unicorn Cupcake","800"},{"Egg Tart","700"},{"DIY and dcorate","700"},{"Strawberry Yogurt","800"},{"Berry Yogurt","800"},
                {"Grape Yogurt","800"},{"Fruity Yogurt","1000"},{"Strawberry Ice_cream","1000"},{"Chocolate Ice_cream","1000"},{"Vanila Ice_cream","1000"},
                {"Sushi","1000"},{"Key_Chain","700"},{"UIT_Book","350"}};
    String output="";
    DefaultTableModel tbTableModel = new DefaultTableModel(new Object[]{"Item No","Item Name","Qty","Amount"},0);
    int price;
    public void addAll()
    {
        cbSale.addItem("Cash");
        cbSale.addItem("Cheque");
        cbSale.addItem("Credit");
       for(int i=0;i<13;i++)
            cbSelected.addItem(item[i][0]);
        //DateLabel myDate = new DateLabel();
        cbSelected.addActionListener(new ActionListener(){
        public void actionPerformed(ActionEvent event){
            JComboBox comboBox=(JComboBox)event.getSource();
            output=item[comboBox.getSelectedIndex()][1];
        lblPrice.setText(output);
        }
        });
        Date date = new Date();
        lblInputDate2.setText(String.valueOf(date.toLocaleString()));
        txtQty.addFocusListener(new FocusListener()
                {
                    public void focusGained(FocusEvent e){
                        lblQtyTitle.setText("Qty");
                        txtQty.setText("0");
                        price = Integer.parseInt(lblPrice.getText());
                        txtQty.setText("");
                    }
                    public void focusLost(FocusEvent e){
                       
                    }
                });
        tblSale.setRowHeight(20);
        tblSale.getTableHeader().setFont(new Font("Tahoma",Font.PLAIN,15));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSale = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInvoice = new javax.swing.JTextField();
        cbSelected = new javax.swing.JComboBox<>();
        lblQtyTitle = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSale = new javax.swing.JTable();
        lblInputDate = new javax.swing.JLabel();
        lblInputDate2 = new javax.swing.JLabel();
        btnEqual = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbSale = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSale.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        txtSale.setForeground(new java.awt.Color(255, 51, 51));
        txtSale.setText("Sales");
        txtSale.setAlignmentX(1000.0F);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Invoice");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Date");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Select Item");

        txtInvoice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtInvoice.setText("AutoIncreament");
        txtInvoice.setEnabled(false);
        txtInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceActionPerformed(evt);
            }
        });

        cbSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cbSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectedActionPerformed(evt);
            }
        });

        lblQtyTitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtQty.setText("Qty");
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("x");

        lblPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrice.setText("Price");

        lblAmount.setText("Amount");

        btnDone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tblSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item No", "Item Name", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblSale);

        lblInputDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblInputDate2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnEqual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Saled By");

        cbSale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Customer Name");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReturn.setText("Return Home");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(btnReturn))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblInputDate2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtInvoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInputDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSale, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblQtyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQty, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(btnEqual)
                        .addGap(18, 18, 18)
                        .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(478, 478, 478))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSale, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(635, 635, 635))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInputDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblQtyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(18, 18, 18)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInputDate)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(158, 158, 158))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed
public int DatbaseSale(int year,int month, int date,String Name,String Item,String acc,String qty,String price3)
{
    String url = "jdbc:mysql://localhost:3306/computerizedaccounting";
    String username = "root";
    String password = "wuttyeetun";
    Connection conn;
    Statement stmt;
    String NameAcc = String.valueOf(txtName.getText())+" A/C";
    System.out.println(NameAcc);
    if(acc!="Cash A/C" && acc!="Cheque A/C" && !acc.equals(NameAcc)){
                            price3=String.valueOf(Integer.parseInt(price3)*(-1));
                           }
    String query="INSERT INTO CUSTOMER(date,cname,item,account,qty,price) VALUES('"+String.valueOf(year)+'/'+String.valueOf(month)+'/'+String.valueOf(date)+"'"+",'"+Name+"','"+Item+"','"+acc+"',"+qty+","+price3+");";
    try{			 
			 conn = DriverManager.getConnection(url, username, password);
			 stmt = conn.createStatement();
                         int res=stmt.executeUpdate(query);	
		     //if(res==1) 
                       // JOptionPane.showMessageDialog(this, "Successfully Insert!");
		     conn.close();
                     return res;
		 }
		 catch (SQLException sqle){
		      System.out.println("SQL Exception thrown: " + sqle);
                      return 0;
		 }
}
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        tbTableModel.getDataVector().removeAllElements();
        tblSale.revalidate();
        tblSale.repaint();
        String Name = String.valueOf(txtName.getText());
        //String acc[] = null;
        String acc[]={"",""};
        Date d=new Date();
        int date = d.getDate();
        int month = d.getMonth()+1;
        int year = d.getYear()+1900;
        String query;
        String Success="";
        String itemName2[]=itemName.split("\n");
        String qty2[]=qty.split("\n");
        if(cbSale.getSelectedItem()=="Cash"){
            acc[0]="Cash A/C";
        }
        else if(cbSale.getSelectedItem()=="Cheque")
            acc[0]="Cheque A/C";
        else if(cbSale.getSelectedItem()=="Credit")
            acc[0]=Name+" A/C";
        String price3[]=price2.split("\n");
        int accControl = 0;
        //acc[1]=
             for(int i=0; i<itemName2.length*2;i++){
                double index = Math.floor(i/2);
                int index2 = (int)index;
                acc[1]=itemName2[index2]+" A/C";
                Success+=String.valueOf(DatbaseSale(year, month, date, Name, itemName2[index2], acc[accControl],qty2[index2] , price3[index2]));
                if(accControl==0)
                    accControl=1;
                else
                    accControl=0;
              }
             if(!Success.contains("0"))
                    JOptionPane.showMessageDialog(this, "Successfully Insert!");
        txtInvoice.setText("");
        txtName.setText("");
        txtQty.setText("");
        total=0;
        itemName="";
        qty="";
        price2="";
        i=1;
    }//GEN-LAST:event_btnSaveActionPerformed
int total=0;int i=1;
        String itemName="", qty="", price2="";
    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        if(i!=1)
        {
          tbTableModel.getDataVector().removeElementAt(i-1);  
        }
        tblSale.setModel(tbTableModel);
        Object []dr={i,cbSelected.getSelectedItem(),txtQty.getText(),lblAmount.getText()};
                i++;
                total+=Integer.parseInt(lblAmount.getText());
            tbTableModel.addRow(dr);
            tbTableModel.addRow(new Object[]{"","Total","",String.valueOf(total)});
            itemName+=cbSelected.getSelectedItem()+"\n";  
            qty+=txtQty.getText()+"\n";
            price2+=lblAmount.getText()+"\n";
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        int amount = price*Integer.parseInt(txtQty.getText());
                     lblAmount.setText(String.valueOf(amount));
    }//GEN-LAST:event_btnEqualActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        Home H=new Home();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        H.setSize(d.width,d.height);
        dispose();
        H.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void cbSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Sale frame = new Sale();
               Dimension screen;
                screen = Toolkit.getDefaultToolkit().getScreenSize();
               frame.setSize(screen.width,screen.height);
               frame.setTitle("Computerized Accounting");
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDone;
    public javax.swing.JButton btnEqual;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    public javax.swing.JComboBox<String> cbSale;
    public javax.swing.JComboBox<String> cbSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblInputDate;
    public javax.swing.JLabel lblInputDate2;
    private javax.swing.JLabel lblPrice;
    public javax.swing.JLabel lblQtyTitle;
    public javax.swing.JTable tblSale;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQty;
    private javax.swing.JLabel txtSale;
    // End of variables declaration//GEN-END:variables
}
